// Fixed, synthetic inputs only. Expected verdicts describe this small suite,
// not a universal correctness benchmark or a calibrated confidence measure.
export const cases = [
  {
    id: 'percentage-bases',
    question: 'Is a 20% increase followed by a 20% decrease a wash?',
    answerA: 'Yes. The percentages cancel, so the final value equals the starting value.',
    answerB: 'No. Starting at 100, the result is 100 times 1.2 times 0.8 = 96, a 4% loss.',
    expected: ['B'],
    explanation: 'The multiplicative factors produce 0.96 of the initial value.',
  },
  {
    id: 'both-correct',
    question: 'What is 12 times 3 in ordinary arithmetic?',
    answerA: '36. Adding 12 + 12 + 12 gives 36.',
    answerB: '36. Distributing gives 10 times 3 plus 2 times 3, or 30 + 6.',
    expected: ['both'],
    explanation: 'Both valid methods compute the same correct integer.',
  },
  {
    id: 'both-wrong',
    question: 'What is 2 + 2 in ordinary base ten integer arithmetic?',
    answerA: '5. Adding two and two makes five.',
    answerB: '6. Adding two and two makes six.',
    expected: ['neither'],
    explanation: 'Both assert an incorrect result; the sum is four.',
  },
  {
    id: 'identical-correct',
    question: 'What is 2 + 2 in ordinary base ten integer arithmetic?',
    answerA: '4.', answerB: '4.', expected: ['both'],
    noReasoning: true,
    explanation: 'Identical correct conclusions have no differences and supply no reasoning.',
  },
  {
    id: 'identical-wrong',
    question: 'What is 2 + 2 in ordinary base ten integer arithmetic?',
    answerA: '5.', answerB: '5.', expected: ['neither'],
    noReasoning: true,
    explanation: 'Identical text does not establish correctness. Both conclusions are wrong.',
  },
  {
    id: 'missing-observation',
    question: 'What is the temperature inside my refrigerator right now? No measurements, sensor readings, or appliance settings are provided.',
    answerA: 'It is 2 degrees Celsius.', answerB: 'It is 8 degrees Celsius.',
    expected: ['insufficient'], noReasoning: true,
    explanation: 'No supplied observation establishes either exact temperature.',
  },
  {
    id: 'conditional-tradeoff',
    question: 'Which courier should I choose? X costs $5 and takes 5 days. Y costs $10 and takes 1 day. I have not specified whether price or speed matters more.',
    answerA: 'Choose X if minimizing price is your goal: it costs $5 instead of $10.',
    answerB: 'Choose Y if minimizing delivery time is your goal: it takes 1 day instead of 5.',
    expected: ['depends', 'both'],
    explanation: 'Both explicitly conditional recommendations are valid. Either a conditional verdict or recognition that both hold up is acceptable.',
  },
  {
    id: 'unknown-preference',
    question: 'Which color would I personally prefer, blue or green? I have not told you anything about my preferences.',
    answerA: 'Blue.', answerB: 'Green.', expected: ['insufficient'],
    noReasoning: true,
    explanation: 'The user has supplied no preference information, so neither prediction is established.',
  },
];
