// Fixed, synthetic inputs only. Expected verdicts describe this small suite,
// not a universal correctness benchmark or a calibrated confidence measure.
export const cases = [
  {
    id: 'percentage-bases',
    question: 'Is a 20% increase followed by a 20% decrease a wash?',
    answerA: 'Yes. The percentages cancel, so the final value equals the starting value.',
    answerB: 'No. Starting at 100, the result is 100 times 1.2 times 0.8 = 96, a 4% loss.',
    expected: ['B'],
    explanation: 'The multiplicative factors produce 0.96 of the initial value.',
  },
  {
    id: 'both-correct',
    question: 'What is 12 times 3 in ordinary arithmetic?',
    answerA: '36. Adding 12 + 12 + 12 gives 36.',
    answerB: '36. Distributing gives 10 times 3 plus 2 times 3, or 30 + 6.',
    expected: ['both'],
    explanation: 'Both valid methods compute the same correct integer.',
  },
  {
    id: 'both-wrong',
    question: 'What is 2 + 2 in ordinary base ten integer arithmetic?',
    answerA: '5. Adding two and two makes five.',
    answerB: '6. Adding two and two makes six.',
    expected: ['neither'],
    explanation: 'Both assert an incorrect result; the sum is four.',
  },
  {
    id: 'identical-correct',
    question: 'What is 2 + 2 in ordinary base ten integer arithmetic?',
    answerA: '4.', answerB: '4.', expected: ['both'],
    noReasoning: true,
    explanation: 'Identical correct conclusions have no differences and supply no reasoning.',
  },
  {
    id: 'identical-wrong',
    question: 'What is 2 + 2 in ordinary base ten integer arithmetic?',
    answerA: '5.', answerB: '5.', expected: ['neither'],
    noReasoning: true,
    explanation: 'Identical text does not establish correctness. Both conclusions are wrong.',
  },
  {
    id: 'missing-observation',
    question: 'What is the temperature inside my refrigerator right now? No measurements, sensor readings, or appliance settings are provided.',
    answerA: 'It is 2 degrees Celsius.', answerB: 'It is 8 degrees Celsius.',
    expected: ['insufficient'], noReasoning: true,
    explanation: 'No supplied observation establishes either exact temperature.',
  },
  {
    id: 'conditional-tradeoff',
    question: 'Which courier should I choose? X costs $5 and takes 5 days. Y costs $10 and takes 1 day. I have not specified whether price or speed matters more.',
    answerA: 'Choose X if minimizing price is your goal: it costs $5 instead of $10.',
    answerB: 'Choose Y if minimizing delivery time is your goal: it takes 1 day instead of 5.',
    expected: ['depends'],
    explanation: 'Version 1.0.2 gives depends precedence when different valid recommendations require an unspecified priority.',
  },
  {
    id: 'unknown-preference',
    question: 'Which color would I personally prefer, blue or green? I have not told you anything about my preferences.',
    answerA: 'Blue.', answerB: 'Green.', expected: ['insufficient'],
    noReasoning: true,
    explanation: 'The user has supplied no preference information, so neither prediction is established.',
  },
  {
    id: 'storage-tradeoff',
    question: 'Which fictional storage plan should I choose? Small costs $3 per month for 20 GB. Large costs $8 per month for 100 GB. I have not specified my capacity needs or whether cost or capacity matters more.',
    answerA: 'Choose Small if your goal is the lowest monthly price and 20 GB is enough: $3 is less than $8.',
    answerB: 'Choose Large if you need more than 20 GB and at most 100 GB: it provides 100 GB rather than 20 GB.',
    expected: ['depends'],
    explanation: 'Known price and capacity tradeoffs need a user requirement to select one option.',
  },
  {
    id: 'specified-priority',
    question: 'Which courier should I choose? X costs $5 and takes 5 days. Y costs $10 and takes 1 day. Delivery within 2 days is mandatory, and my budget is $10. Treat these times and prices as guaranteed.',
    answerA: 'Choose X because it costs only $5, which is cheaper than Y.',
    answerB: 'Choose Y because its 1 day delivery meets your deadline and its $10 price fits your budget. X takes 5 days and misses the deadline.',
    expected: ['B'],
    explanation: 'The supplied mandatory deadline resolves the tradeoff; only Y meets it.',
  },
  {
    id: 'same-conditions-recommendation',
    question: 'Which box meets my requirement of at least 8 liters? Box P holds 10 liters and box Q holds 5 liters. Capacity is my only criterion.',
    answerA: 'Choose P. Its 10 liter capacity is at least 8 liters, while Q holds only 5 liters.',
    answerB: 'P meets the requirement: it has 2 liters more than the minimum. Q is 3 liters short.',
    expected: ['both'],
    explanation: 'Both recommendations are correct under the same explicit criterion.',
  },
];
